# Generated by Django 4.0.2 on 2022-02-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_teacherprofile_experience'),
        ('grade_and_subject', '0005_alter_grade_grade_name'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_and_subject.grade'),
        ),
        migrations.AlterField(
            model_name='post',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_post', to='authentication.teacherprofile'),
        ),
    ]
