# Generated by Django 4.0.2 on 2022-02-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_teacherprofile_experience'),
        ('posts', '0003_comment_updated_at_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='responsed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacherprofile'),
        ),
    ]
