# Generated by Django 4.0.2 on 2022-02-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_teacherprofile_experience'),
        ('posts', '0004_comment_responsed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.studentprofile'),
        ),
    ]
