# Generated by Django 4.0.2 on 2022-02-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_grade_alter_post_teacher'),
        ('posts', '0005_alter_comment_comment_by'),
    ]

    operations = [
    ]
