# Generated by Django 4.0.2 on 2022-03-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_schoolprofile_phone_number_and_more'),
        ('posts', '0009_remove_comment_parent_commentreplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreplies',
            name='respond_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacherprofile'),
        ),
    ]
