# Generated by Django 4.0.2 on 2022-02-09 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade_and_subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('Nursery', 'Nursery'), ('L.K.G', 'L.K.G'), ('U.K.G', 'U.K.G'), ('One', 'One(1)'), ('Two', 'Two(2)'), ('Three', 'Three(3)'), ('Four', 'Four(4)'), ('Five', 'Five(5)'), ('Six', 'Six(6)'), ('Seven', 'Seven(7)'), ('Eight', 'Eight(8)'), ('Nine', 'Nine(9)'), ('Ten', 'Ten(10)'), ('Eleven', 'Eleven(11)'), ('Twelve', 'Twelve(12)')], default='One', max_length=10)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade_and_subject.subjects')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'TE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_SQ', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('Nursery', 'Nursery'), ('L.K.G', 'L.K.G'), ('U.K.G', 'U.K.G'), ('One', 'One(1)'), ('Two', 'Two(2)'), ('Three', 'Three(3)'), ('Four', 'Four(4)'), ('Five', 'Five(5)'), ('Six', 'Six(6)'), ('Seven', 'Seven(7)'), ('Eight', 'Eight(8)'), ('Nine', 'Nine(9)'), ('Ten', 'Ten(10)'), ('Eleven', 'Eleven(11)'), ('Twelve', 'Twelve(12)')], default='One', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('total_question', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=False)),
                ('quiz_duration', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('attended_users', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'ST'}, related_name='attended_user', to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade_and_subject.subjects')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'TE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(blank=True)),
                ('option1', models.CharField(max_length=250)),
                ('option2', models.CharField(max_length=250)),
                ('option3', models.CharField(max_length=250)),
                ('option4', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('attended_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcqs.quiz')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='AttemptedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark_obtain', models.PositiveSmallIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcqs.quiz')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'ST'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveSmallIntegerField(default=1)),
                ('user_answer', models.CharField(blank=True, max_length=150, null=True)),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionanswer', to='mcqs.questions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
