# Generated by Django 3.2.11 on 2022-02-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('mcqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentprofile'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='attended_users',
            field=models.ManyToManyField(blank=True, to='authentication.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='attended_users',
            field=models.ManyToManyField(blank=True, related_name='attended_user', to='authentication.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_quiz', to='authentication.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='shortquestion',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_SQ', to='authentication.teacherprofile'),
        ),
    ]
