# Generated by Django 4.0.2 on 2022-02-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0005_alter_quiz_grade_alter_shortquestion_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortquestion',
            name='quiz',
        ),
    ]
