# Generated by Django 4.0.2 on 2022-02-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_studentprofile_grade'),
        ('mcqs', '0006_remove_shortquestion_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_answer', models.CharField(blank=True, max_length=150, null=True)),
                ('answer_file', models.FileField(upload_to='')),
                ('short_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortquestionanswer', to='mcqs.shortquestion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
