# Generated by Django 4.0.2 on 2022-02-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0008_alter_shortanswersheet_answer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz', to='mcqs.quiz'),
        ),
    ]
