# Generated by Django 4.0.2 on 2022-03-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_schoolprofile_phone_number_and_more'),
        ('mcqs', '0009_alter_questions_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortanswersheet',
            name='mark_ob',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='shortquestion',
            name='attended_users',
            field=models.ManyToManyField(blank=True, to='authentication.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='shortanswersheet',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
