# Generated by Django 3.2.11 on 2022-02-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_and_subject', '0003_auto_20220210_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(choices=[('NUR', 'Nursery'), ('LKG', 'L.K.G'), ('UKG', 'U.K.G'), ('1', 'One(1)'), ('2', 'Two(2)'), ('3', 'Three(3)'), ('4', 'Four(4)'), ('5', 'Five(5)'), ('6', 'Six(6)'), ('7', 'Seven(7)'), ('8', 'Eight(8)'), ('9', 'Nine(9)'), ('10', 'Ten(10)'), ('11', 'Eleven(11)'), ('12', 'Twelve(12)')], default='1', max_length=10),
        ),
    ]
