# Generated by Django 4.0.2 on 2022-02-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_and_subject', '0005_alter_grade_grade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='admission_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='extra_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='monthly_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
