# Generated by Django 4.0.2 on 2022-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_and_subject', '0006_grade_admission_fee_grade_extra_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ManyToManyField(related_name='sub_grade', to='grade_and_subject.Subjects'),
        ),
    ]
