# Generated by Django 4.0.2 on 2022-03-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_and_subject', '0008_classroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroutine',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
