# Generated by Django 4.0.2 on 2022-03-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_and_subject', '0009_classroutine_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_teacher',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
