# Generated by Django 4.0.2 on 2022-03-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_and_subject', '0010_remove_grade_school_remove_subjects_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='class_teacher',
        ),
    ]
