# Generated by Django 3.2.11 on 2022-02-08 10:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_mail_register', ckeditor.fields.RichTextField(help_text='required keywords: [CODE],[EMAIL],[USERNAME]')),
                ('send_mail_password_reset', ckeditor.fields.RichTextField(help_text='required keywords: [CODE],[EMAIL],[USERNAME]', null=True)),
                ('send_mail_verifed', ckeditor.fields.RichTextField(help_text='required keywords: [EMAIL],[USERNAME]', null=True)),
                ('send_mail_password_change', ckeditor.fields.RichTextField(help_text='required keywords: [EMAIL],[USERNAME]', null=True)),
                ('send_mail_order', ckeditor.fields.RichTextField(help_text='required keywords: [EMAIL],[PRODUCT],[PRICE],[USERNAME]', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMTPSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, help_text='Use the app password not your actual password for the security reason.', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
