# Generated by Django 3.2.11 on 2022-02-08 10:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtemplate',
            name='send_mail_order',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='send_mail_password_change',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='send_mail_password_reset',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='send_mail_register',
        ),
        migrations.RemoveField(
            model_name='mailtemplate',
            name='send_mail_verifed',
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='send_mail',
            field=ckeditor.fields.RichTextField(default=None, help_text='required keywords: [EMAIL],[USERNAME],[PASSWORD]'),
            preserve_default=False,
        ),
    ]
