# Generated by Django 4.0.2 on 2022-06-15 11:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0003_aboutus_cms_contactusform_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageNagarAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage-admin/')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSchoolAdmindmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage-school/')),
            ],
        ),
    ]
