# Generated by Django 4.0.2 on 2022-06-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0004_homepagenagaradmin_homepageschooladmindmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageSchoolAdmindmin',
            new_name='HomePageSchoolAdmin',
        ),
    ]
