# Generated by Django 4.0.2 on 2022-06-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0005_rename_homepageschooladmindmin_homepageschooladmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageSchoolAdmin',
        ),
    ]
