# Generated by Django 4.0.2 on 2022-02-10 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Nursery', 'Nursery'), ('L.K.G', 'L.K.G'), ('U.K.G', 'U.K.G'), ('One', 'One(1)'), ('Two', 'Two(2)'), ('Three', 'Three(3)'), ('Four', 'Four(4)'), ('Five', 'Five(5)'), ('Six', 'Six(6)'), ('Seven', 'Seven(7)'), ('Eight', 'Eight(8)'), ('Nine', 'Nine(9)'), ('Ten', 'Ten(10)'), ('Eleven', 'Eleven(11)'), ('Twelve', 'Twelve(12)')], default='One', max_length=10)),
                ('notes_pdf', models.FileField(upload_to=notes.models.get_upload_path)),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchs.subjects')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'TE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
