# Generated by Django 4.0.2 on 2022-02-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade_and_subject', '0004_alter_grade_grade_name'),
        ('notes', '0002_auto_20220211_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade_and_subject.grade'),
        ),
    ]
