# Generated by Django 4.0.2 on 2022-03-03 05:23

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes_pdf',
            field=models.FileField(blank=True, null=True, upload_to=notes.models.get_upload_path),
        ),
    ]
