# Generated by Django 4.0.2 on 2022-02-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_pdf',
        ),
    ]
