# Generated by Django 4.0.2 on 2022-02-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_notice_notice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_pdf',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='notice_pdf'),
        ),
    ]
