# Generated by Django 4.0.2 on 2022-02-10 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0004_rename_notice_pdf_notice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='school',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_notice', to=settings.AUTH_USER_MODEL),
        ),
    ]
