# Generated by Django 4.0.2 on 2022-02-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_alter_notice_pdf_alter_notice_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='posted_by',
        ),
    ]
