# Generated by Django 4.0.2 on 2022-02-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_teacherprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
