# Generated by Django 4.0.2 on 2022-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_studentprofile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
