# Generated by Django 4.0.2 on 2022-02-28 06:46

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_teacherprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.SchoolProfile.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
