# Generated by Django 4.0.2 on 2022-03-22 11:57

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, validators=[authentication.models.only_int]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[authentication.models.only_int]),
        ),
    ]
