# Generated by Django 4.0.2 on 2022-06-19 06:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_imagegallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage-school/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.schoolprofile')),
            ],
        ),
    ]
