# Generated by Django 4.0.2 on 2022-06-19 07:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_homepageschooladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
