# Generated by Django 3.2.11 on 2022-02-10 06:27

from django.db import migrations, models
import django.db.models.deletion
import study_material.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('published_by', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('link', models.URLField(max_length=100)),
                ('pdf', models.FileField(blank=True, max_length=254, null=True, upload_to=study_material.models.StudyMaterial.get_upload_path)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('approved', models.BooleanField(default=True)),
                ('publish', models.BooleanField(default=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.schoolprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
