# Generated by Django 4.0.2 on 2022-03-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material', '0002_alter_studymaterial_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
