# Generated by Django 4.0.2 on 2022-03-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0002_alter_mailboxes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxes',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
