# Generated by Django 4.0.2 on 2022-03-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0003_mailboxes_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxes',
            name='draft',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mailboxes',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailboxes',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
