# Generated by Django 4.0.2 on 2022-03-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0004_mailboxes_draft_mailboxes_important_mailboxes_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailboxes',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
