# Generated by Django 4.0.2 on 2022-02-13 11:56

from django.db import migrations, models
import django.db.models.deletion
import marksheet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('grade_and_subject', '0004_alter_grade_grade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('routine', models.FileField(blank=True, max_length=254, null=True, upload_to=marksheet.models.Exam.get_upload_path)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.schoolprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('NUR', 'Nursery'), ('LKG', 'L.K.G'), ('UKG', 'U.K.G'), ('1', 'One(1)'), ('2', 'Two(2)'), ('3', 'Three(3)'), ('4', 'Four(4)'), ('5', 'Five(5)'), ('6', 'Six(6)'), ('7', 'Seven(7)'), ('8', 'Eight(8)'), ('9', 'Nine(9)'), ('10', 'Ten(10)'), ('11', 'Eleven(11)'), ('12', 'Twelve(12)')], default='1', max_length=10)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_marksheet', to='marksheet.exam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obtain_mark', models.FloatField(default=1)),
                ('pass_mark', models.FloatField(default=32)),
                ('full_mark', models.FloatField(default=100)),
                ('marksheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_marksheet', to='authentication.studentprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_marksheet', to='authentication.studentprofile')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade_and_subject.subjects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
