# Generated by Django 4.0.2 on 2022-02-14 07:28

from django.db import migrations, models
import marksheet.models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='file',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=marksheet.models.Marksheet.get_upload_path),
        ),
    ]
