# Generated by Django 4.0.2 on 2022-02-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0002_marksheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marksheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_marksheet', to='marksheet.marksheet'),
        ),
    ]
