# Generated by Django 4.0.2 on 2022-02-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade_and_subject', '0004_alter_grade_grade_name'),
        ('marksheet', '0003_alter_marks_marksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade_and_subject.grade'),
        ),
    ]
