# Generated by Django 4.0.2 on 2022-02-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0007_remove_marks_student_alter_marks_marksheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
