# Generated by Django 4.0.2 on 2022-02-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0008_marks_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='student',
        ),
    ]
