# Generated by Django 4.0.2 on 2022-02-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade_and_subject', '0005_alter_grade_grade_name'),
        ('marksheet', '0010_remove_marks_pass_mark_alter_marks_full_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_marksheet', to='marksheet.exam'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grade_and_subject.grade'),
        ),
    ]
