# Generated by Django 4.0.2 on 2022-02-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_curriculum_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
