# Generated by Django 3.2.11 on 2022-02-10 15:18

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_curriculum_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='pdf',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=curriculum.models.Curriculum.get_upload_path),
        ),
    ]
