# Generated by Django 4.0.2 on 2022-02-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_curriculum_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
